### ISSUE TITLE
UI does not switch to scoreboard automatically

### ISSUE THREAD

**Issue by jDomantas** [dariuskrtn/pacman-web#13]
* There's an open level
* Open UI
* Wait until all submissions finish playing
* Close level (postman /api/admin/levelstate - close)
* UI should switch to scoreboard view (but it does not)

**Comment by jDomantas** [comment]
This works if you close the level before opening UI:

* There's an open level
* Close level (postman /api/admin/levelstate - close)
* Open UI
* Wait until all submissions finish playing
* UI switches to scoreboard view (as it should)

**Comment by dariuskrtn** [comment]
Check if works now
