### ISSUE TITLE
UI does not switch to new level automatically

### ISSUE THREAD

**Issue by jDomantas** [dariuskrtn/pacman-web#14]
* There's a closed level
* Open UI
* Wait until all submissions finish playing
* UI switches to scoreboard view (as it should)
* Post a new level
* UI should switch to new level (but it does not)

**Comment by dariuskrtn** [comment]
submit big level
then submit small level
Outcome: small level blocks are the same size as the big one's

**Comment by dariuskrtn** [comment]
looks ok after refresh
