### ISSUE TITLE
White stripes sometimes appear on the simulation canvas

### ISSUE THREAD

**Issue by vstrimaitis** [dariuskrtn/pacman-web#15]
When the window is of a certain size, gaps between grid cells in the simulation canvas appear.

![Capture](https://user-images.githubusercontent.com/14166032/59103825-90154e00-8938-11e9-844a-fe2949874447.PNG)

**Comment by jDomantas** [comment]
Idea for a fix:
* Make all floor and wall tiles extend 1px outwards.
* Draw all floor tiles after all wall tiles.
