### ISSUE TITLE
Level switching is broken-ish

### ISSUE THREAD

**Issue by jDomantas** [dariuskrtn/pacman-web#20]
* POST a level
* Open UI
* Submit a solution. UI will pick it up and show the simulation (it will be shown as submission 0).
* After simulation is finished, POST a new level.
* UI shows new level.
* Submit a solution.
* Nothing happens (UI should show this as submission 0).
* Submit another solution.
* UI starts showing this as submission 1.
* Clicking "previous" back shows submission 0, but it's the submission from previous level (it should be first submission of this level).

**Comment by dariuskrtn** [comment]
fixed?
